title: Trial Website on GitHub
author: Ada Fractal
email: adafractal@email.com
description: > # this means to ignore newlines until "baseurl:"
  This is an awesome description for a somewhat awesome page (I mean, not really)
  It's a trial run, trying to see how GitHub websites work. 
  
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
